### ISSUE TITLE
Example not working on 0.21.

### ISSUE THREAD

**Issue by keybrdist** [AzuraCast/example-plugin#8]
`git clone https://github.com/AzuraCast/example-plugin.git ./azuracast/plugins/example-plugin`

docker-compose.override.yml
```dockerfile
environment:
    - AZURACAST_PLUGIN_MODE=true
volumes:
    - ./azuracast/plugins/example-plugin:/var/azuracast/www/plugins/example-plugin
```

azuracast  | [2024-07-09T07:07:29.911594+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class "Plugin\ExamplePlugin\EventHandler\AllTheListeners" not found in /var/azuracast/www/plugins/example-plugin/events.php:33 Stack trace: #0 [internal function]: App\Plugins::{closure}(Object(App\CallableEventDispatcher)) #1 /var/azuracast/www/src/Plugins.php(79): call_user_func(Object(Closure), Object(App\CallableEventDispatcher)) #2 /var/azuracast/www_tmp/CompiledContainer.php(375): App\Plugins->registerEvents(Object(App\CallableEventDispatcher)) #3 [internal function]: CompiledContainer::{closure}(Object(CompiledContainer), Object(App\Plugins)) #4 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array) #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array) #6 /var/azuracast/www_tmp/CompiledContainer.php(362): DI\CompiledContainer->resolveFactory(Object(Closure), 'App\\CallableEve...') #7 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get17() #8 /var/azuracast/www_tmp/CompiledContainer.php(383): DI\CompiledContainer->get('App\\CallableEve...') #9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get18() #10 /var/azuracast/www/src/AppFactory.php(69): DI\CompiledContainer->get('Psr\\EventDispat...') #11 /var/azuracast/www/src/AppFactory.php(39): App\AppFactory::buildAppFromContainer(Object(CompiledContainer)) #12 /var/azuracast/www/bin/console(11): App\AppFactory::createCli() #13 {main}   thrown {"code":1,"message":"Uncaught Error: Class \"Plugin\\ExamplePlugin\\EventHandler\\AllTheListeners\" not found in /var/azuracast/www/plugins/example-plugin/events.php:33\nStack trace:\n#0 [internal function]: App\\Plugins::{closure}(Object(App\\CallableEventDispatcher))\n#1 /var/azuracast/www/src/Plugins.php(79): call_user_func(Object(Closure), Object(App\\CallableEventDispatcher))\n#2 /var/azuracast/www_tmp/CompiledContainer.php(375): App\\Plugins->registerEvents(Object(App\\CallableEventDispatcher))\n#3 [internal function]: CompiledContainer::{closure}(Object(CompiledContainer), Object(App\\Plugins))\n#4 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\\Invoker->call(Object(Closure), Array)\n#6 /var/azuracast/www_tmp/CompiledContainer.php(362): DI\\CompiledContainer->resolveFactory(Object(Closure), 'App\\\\CallableEve...')\n#7 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get17()\n#8 /var/azuracast/www_tmp/CompiledContainer.php(383): DI\\CompiledContainer->get('App\\\\CallableEve...')\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get18()\n#10 /var/azuracast/www/src/AppFactory.php(69): DI\\CompiledContainer->get('Psr\\\\EventDispat...')\n#11 /var/azuracast/www/src/AppFactory.php(39): App\\AppFactory::buildAppFromContainer(Object(CompiledContainer))\n#12 /var/azuracast/www/bin/console(11): App\\AppFactory::createCli()\n#13 {main}\n  thrown","file":"/var/azuracast/www/plugins/example-plugin/events.php","line":33,"trace":null} []

**Comment by djakobi** [comment]
+1

**Comment by benmwilson** [comment]
+1
